# Lambda Stack
Parameters: 
  AccessPointResourceArn: 
    Type: String
  SpiceQlSgId:
    Type: String
  SpiceQlRestfulApiId:
    Type: String
  SpiceQlRedisEndpoint:
    Type: String
Resources:

  #spiceql endpoint
  SpiceQLambdaDev:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: spiceqlambdadev
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_handler"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  SpiceQLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SpiceQLambdaDev
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SpiceQLambdaDev
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/spiceql"

  #strSclkToEt endpoint
  StrSclkToEtLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: strSclkToEtlambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_strSclkToEt"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  StrSclkToEtLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StrSclkToEtLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/strSclkToEt"

  #doubleSclkToEt endpoint
  DoubleSclkToEtLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: doubleSclkToEtlambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_doubleSclkToEt"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  DoubleSclkToEtLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DoubleSclkToEtLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/doubleSclkToEt"
 
  #utcToEt endpoint
  UtcToEtLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: utcToEtlambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_utcToEt"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  UtcToEtLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UtcToEtLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/utcToEt"

  #translateNameToCode endpoint
  TranslateNameToCodeLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: translateNameToCodelambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_translateNameToCode"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  TranslateNameToCodeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TranslateNameToCodeLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/translateNameToCode"
  
  #translateCodeToName endpoint
  TranslateCodeToNameLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: translateCodeToNamelambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_translateCodeToName"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  TranslateCodeToNameLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TranslateCodeToNameLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/translateCodeToName"


  #getTargetStates endpoint
  GetTargetStatesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: getTargetStateslambda
      PackageType: Image
      MemorySize: 2000
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_getTargetStates"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  GetTargetStatesLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTargetStatesLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/getTargetStates"

  #getTargetOrientations endpoint
  GetTargetOrientationsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: getTargetOrientationslambda
      PackageType: Image
      MemorySize: 2000
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_getTargetOrientations"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  GetTargetOrientationsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTargetOrientationsLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/getTargetOrientations"

  #frameTrace endpoint
  FrameTraceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: frameTracelambda
      PackageType: Image
      MemorySize: 2000
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_frameTrace"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  FrameTraceLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FrameTraceLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/frameTrace"

  #findMissionKeywords endpoint
  findMissionKeywordsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: findMissionKeywordslambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_findMissionKeywords"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  findMissionKeywordsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref findMissionKeywordsLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/findMissionKeywords"


  #findTargetKeywords endpoint
  findTargetKeywordsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: findTargetKeywordslambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_findTargetKeywords"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: "spiceqlelasticachecluster.wufcwa.clustercfg.usw2.cache.amazonaws.com"
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  findTargetKeywordsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref findTargetKeywordsLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/findTargetKeywords"


  #getFrameInfo endpoint
  GetFrameInfoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: getFrameInfolambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_getFrameInfo"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  GetFrameInfoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetFrameInfoLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/getFrameInfo"


  #GetTargetFrameInfo endpoint
  GetTargetFrameInfoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 300 
      Role: arn:aws:iam::950438895271:role/csr-Lambda-Role
      FunctionName: getTargetFrameInfolambda
      PackageType: Image
      FileSystemConfigs: 
        - Arn: !Ref AccessPointResourceArn
          LocalMountPath: '/mnt/isis_data'
      ImageConfig:
        Command: ["lambda_function.lambda_getTargetFrameInfo"]
      Code:
        ImageUri: 950438895271.dkr.ecr.us-west-2.amazonaws.com/spiceql:latest
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SpiceQlSgId 
        SubnetIds: 
          - subnet-0326c18b7c38caa73
      Environment:
        Variables: 
          SPICEQL_REDIS_HOST: !Ref SpiceQlRedisEndpoint
          SPICEQL_REDIS_PORT: 6379
          SPICEQL_LOG_LEVEL: trace
          SPICEQL_ENABLE_REDIS: true
  GetTargetFrameInfoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTargetFrameInfoLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-west-2:950438895271:${SpiceQlRestfulApiId}/*/GET/getTargetFrameInfo"
